// Sample data for Sierra Leonean recipes
import type { Recipe } from "./types"

export const recipes: Recipe[] = [
  {
    id: "1",
    name: "Cassava Leaf Soup",
    description:
      "A traditional Sierra Leonean dish made with cassava leaves and a variety of meats and fish. This hearty soup is typically served with rice and is a staple in Sierra Leonean cuisine.",
    image: "/images/cassava-leaf.jpg",
    cookTime: 120,
    servings: 6,
    approvalRating: 95,
    votes: 124,
    ingredients: [
      { name: "cassava leaves", quantity: "2 lbs" },
      { name: "palm oil", quantity: "1/2 cup" },
      { name: "beef", quantity: "1 lb" },
      { name: "chicken", quantity: "1 lb" },
      { name: "dried fish", quantity: "1/2 lb" },
      { name: "onions", quantity: "2 medium" },
      { name: "hot peppers", quantity: "2-3" },
      { name: "salt", quantity: "to taste" },
      { name: "Maggi cubes", quantity: "2" },
    ],
    instructions: [
      "Clean and wash the cassava leaves thoroughly. If using fresh leaves, pound or blend them until smooth.",
      "Cut the beef and chicken into bite-sized pieces.",
      "In a large pot, heat the palm oil over medium heat.",
      "Add the onions and sauté until translucent.",
      "Add the meat and cook until browned on all sides.",
      "Add the cassava leaves, dried fish, hot peppers, salt, and Maggi cubes.",
      "Add enough water to cover the ingredients and bring to a boil.",
      "Reduce heat and simmer for 1-2 hours, stirring occasionally, until the soup thickens and the meat is tender.",
      "Serve hot with rice.",
    ],
    tips: [
      "For an authentic taste, use fresh cassava leaves if available.",
      "The soup should be thick and not watery.",
      "You can substitute spinach for cassava leaves if they're not available.",
    ],
    categories: ["Main Dish", "Soup", "Traditional"],
    author: {
      name: "Aminata Kamara",
      avatar: "/images/avatar-1.jpg",
      bio: "Born and raised in Freetown, I love sharing authentic Sierra Leonean recipes passed down through generations.",
      recipesCount: 15,
    },
    comments: [
      {
        id: "c1",
        author: {
          name: "John Smith",
          avatar: "/images/avatar-2.jpg",
        },
        content: "I tried this recipe and it was delicious! Very authentic taste.",
        date: "2 weeks ago",
      },
      {
        id: "c2",
        author: {
          name: "Maria Garcia",
          avatar: "/images/avatar-3.jpg",
        },
        content:
          "The cassava leaves were hard to find, but I substituted with spinach as suggested and it was still great!",
        date: "1 month ago",
      },
    ],
  },
  {
    id: "2",
    name: "Jollof Rice",
    description:
      "A popular West African rice dish cooked in a flavorful tomato and pepper sauce. Sierra Leonean jollof rice often includes meat or fish and is served at celebrations and gatherings.",
    image: "/images/jollof-rice.jpg",
    cookTime: 60,
    servings: 8,
    approvalRating: 92,
    votes: 98,
    ingredients: [
      { name: "long grain rice", quantity: "4 cups" },
      { name: "tomatoes", quantity: "6 medium" },
      { name: "red bell peppers", quantity: "2" },
      { name: "onions", quantity: "3 large" },
      { name: "vegetable oil", quantity: "1/2 cup" },
      { name: "chicken stock", quantity: "4 cups" },
      { name: "curry powder", quantity: "1 tbsp" },
      { name: "thyme", quantity: "1 tsp" },
      { name: "bay leaves", quantity: "2" },
      { name: "salt", quantity: "to taste" },
    ],
    instructions: [
      "Blend the tomatoes, red bell peppers, and one onion until smooth.",
      "Dice the remaining onions.",
      "Heat the vegetable oil in a large pot over medium heat.",
      "Add the diced onions and sauté until translucent.",
      "Pour in the blended tomato mixture and cook for 10-15 minutes until reduced.",
      "Add the curry powder, thyme, bay leaves, and salt. Stir well.",
      "Add the rice and stir until well coated with the sauce.",
      "Pour in the chicken stock, cover, and bring to a boil.",
      "Reduce heat to low and simmer for 25-30 minutes until the rice is cooked and the liquid is absorbed.",
      "Fluff the rice with a fork and serve hot.",
    ],
    tips: [
      "Wash the rice thoroughly before cooking to remove excess starch.",
      "For extra flavor, you can add chicken, beef, or fish to the dish.",
      "The rice should be slightly sticky but not mushy.",
    ],
    categories: ["Main Dish", "Rice", "Party Food"],
    author: {
      name: "Ibrahim Koroma",
      avatar: "/images/avatar-4.jpg",
      bio: "Chef and food enthusiast specializing in West African cuisine.",
      recipesCount: 22,
    },
    comments: [
      {
        id: "c3",
        author: {
          name: "Sarah Johnson",
          avatar: "/images/avatar-5.jpg",
        },
        content: "This jollof rice is amazing! So flavorful and authentic.",
        date: "3 days ago",
      },
    ],
  },
  {
    id: "3",
    name: "Groundnut Stew",
    description:
      "A rich and creamy peanut-based stew that's popular throughout Sierra Leone. Made with meat, vegetables, and ground peanuts, it's hearty and full of flavor.",
    image: "/images/groundnut-stew.jpg",
    cookTime: 90,
    servings: 6,
    approvalRating: 88,
    votes: 76,
    ingredients: [
      { name: "chicken", quantity: "2 lbs" },
      { name: "natural peanut butter", quantity: "1 cup" },
      { name: "tomatoes", quantity: "4 medium" },
      { name: "onions", quantity: "2 large" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "ginger", quantity: "1 inch piece" },
      { name: "chicken stock", quantity: "4 cups" },
      { name: "sweet potatoes", quantity: "2 medium" },
      { name: "spinach", quantity: "2 cups" },
      { name: "vegetable oil", quantity: "1/4 cup" },
      { name: "salt", quantity: "to taste" },
    ],
    instructions: [
      "Cut the chicken into bite-sized pieces.",
      "Blend the tomatoes, one onion, garlic, and ginger until smooth.",
      "Dice the remaining onion and cut the sweet potatoes into cubes.",
      "Heat the oil in a large pot over medium heat.",
      "Add the diced onion and sauté until translucent.",
      "Add the chicken and cook until browned on all sides.",
      "Pour in the blended tomato mixture and cook for 10 minutes.",
      "Add the chicken stock and bring to a boil.",
      "Stir in the peanut butter until well combined.",
      "Add the sweet potatoes and simmer for 20-25 minutes until tender.",
      "Add the spinach and cook for another 5 minutes.",
      "Season with salt to taste and serve hot with rice.",
    ],
    tips: [
      "Use natural peanut butter without added sugar or salt for the best flavor.",
      "You can substitute chicken with beef or goat meat.",
      "For a spicier stew, add some hot peppers.",
    ],
    categories: ["Main Dish", "Stew", "Traditional"],
    author: {
      name: "Fatmata Sesay",
      avatar: "/images/avatar-6.jpg",
      bio: "Cooking enthusiast sharing traditional Sierra Leonean recipes from my grandmother's kitchen.",
      recipesCount: 8,
    },
    comments: [
      {
        id: "c4",
        author: {
          name: "David Wilson",
          avatar: "/images/avatar-7.jpg",
        },
        content: "This stew is incredible! The peanut flavor is perfect.",
        date: "1 week ago",
      },
    ],
  },
  {
    id: "4",
    name: "Okra Soup",
    description:
      "A slimy, nutritious soup made with okra, fish, and meat. It's a popular dish in Sierra Leone, often served with rice or fufu.",
    image: "/images/okra-soup.jpg",
    cookTime: 60,
    servings: 4,
    approvalRating: 85,
    votes: 62,
    ingredients: [
      { name: "okra", quantity: "1 lb" },
      { name: "beef", quantity: "1/2 lb" },
      { name: "fish", quantity: "1/2 lb" },
      { name: "palm oil", quantity: "1/4 cup" },
      { name: "onions", quantity: "1 large" },
      { name: "hot peppers", quantity: "1-2" },
      { name: "salt", quantity: "to taste" },
      { name: "Maggi cubes", quantity: "2" },
    ],
    instructions: [
      "Cut the okra into small rounds.",
      "Cut the beef into bite-sized pieces.",
      "Clean and cut the fish into portions.",
      "In a large pot, heat the palm oil over medium heat.",
      "Add the onions and sauté until translucent.",
      "Add the beef and cook until browned.",
      "Add enough water to cover the meat and bring to a boil.",
      "Reduce heat and simmer for 20 minutes until the meat is tender.",
      "Add the fish, okra, hot peppers, salt, and Maggi cubes.",
      "Simmer for another 15-20 minutes until the okra is soft and the soup is slimy.",
      "Serve hot with rice or fufu.",
    ],
    tips: [
      "The sliminess of the okra is a desired quality in this soup.",
      "You can add smoked fish for extra flavor.",
      "Fresh okra works best for this recipe.",
    ],
    categories: ["Soup", "Traditional", "Seafood"],
    author: {
      name: "Mohamed Bangura",
      avatar: "/images/avatar-8.jpg",
      bio: "Fisherman and cook from Freetown, specializing in seafood dishes.",
      recipesCount: 12,
    },
    comments: [
      {
        id: "c5",
        author: {
          name: "Lisa Brown",
          avatar: "/images/avatar-9.jpg",
        },
        content: "I was hesitant about the sliminess, but it's actually delicious!",
        date: "2 months ago",
      },
    ],
  },
  {
    id: "5",
    name: "Plasas (Sweet Potato Leaf Stew)",
    description:
      "A nutritious stew made with sweet potato leaves, fish, and meat. It's a staple in Sierra Leonean cuisine and is typically served with rice.",
    image: "/images/plasas.jpg",
    cookTime: 90,
    servings: 6,
    approvalRating: 90,
    votes: 84,
    ingredients: [
      { name: "sweet potato leaves", quantity: "2 lbs" },
      { name: "palm oil", quantity: "1/2 cup" },
      { name: "beef", quantity: "1/2 lb" },
      { name: "dried fish", quantity: "1/2 lb" },
      { name: "onions", quantity: "2 medium" },
      { name: "hot peppers", quantity: "2-3" },
      { name: "salt", quantity: "to taste" },
      { name: "Maggi cubes", quantity: "2" },
    ],
    instructions: [
      "Clean and wash the sweet potato leaves thoroughly. Remove any tough stems.",
      "Cut the beef into bite-sized pieces.",
      "In a large pot, heat the palm oil over medium heat.",
      "Add the onions and sauté until translucent.",
      "Add the beef and cook until browned on all sides.",
      "Add the sweet potato leaves, dried fish, hot peppers, salt, and Maggi cubes.",
      "Add enough water to cover the ingredients and bring to a boil.",
      "Reduce heat and simmer for 1-1.5 hours, stirring occasionally, until the stew thickens and the meat is tender.",
      "Serve hot with rice.",
    ],
    tips: [
      "You can substitute spinach or kale if sweet potato leaves are not available.",
      "The stew should be thick and not watery.",
      "For extra flavor, add some smoked fish.",
    ],
    categories: ["Main Dish", "Stew", "Traditional"],
    author: {
      name: "Aminata Kamara",
      avatar: "/images/avatar-1.jpg",
      bio: "Born and raised in Freetown, I love sharing authentic Sierra Leonean recipes passed down through generations.",
      recipesCount: 15,
    },
    comments: [
      {
        id: "c6",
        author: {
          name: "Robert Chen",
          avatar: "/images/avatar-10.jpg",
        },
        content: "This is now one of my favorite dishes! So flavorful and nutritious.",
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: "6",
    name: "Foo-Foo with Sauce",
    description:
      "A traditional Sierra Leonean dish made from cassava or plantain flour. It's typically served with a flavorful sauce and is eaten with the hands.",
    image: "/images/foo-foo.jpg",
    cookTime: 45,
    servings: 4,
    approvalRating: 82,
    votes: 58,
    ingredients: [
      { name: "cassava flour", quantity: "4 cups" },
      { name: "water", quantity: "6 cups" },
      { name: "salt", quantity: "1 tsp" },
    ],
    instructions: [
      "Bring 3 cups of water to a boil in a large pot.",
      "In a separate bowl, mix the cassava flour with the remaining 3 cups of cold water to form a smooth paste.",
      "Slowly pour the paste into the boiling water, stirring continuously to prevent lumps.",
      "Add salt and continue stirring until the mixture thickens and becomes smooth.",
      "Reduce heat to low and cover the pot. Let it cook for 15-20 minutes, stirring occasionally.",
      "The foo-foo is ready when it's firm and can be shaped.",
      "Serve hot with your choice of sauce or soup.",
    ],
    tips: [
      "Traditionally, foo-foo is eaten with clean hands by pinching off a small piece and dipping it into the sauce.",
      "You can also use plantain flour instead of cassava flour.",
      "The consistency should be firm enough to shape but not too dry.",
    ],
    categories: ["Side Dish", "Traditional"],
    author: {
      name: "Ibrahim Koroma",
      avatar: "/images/avatar-4.jpg",
      bio: "Chef and food enthusiast specializing in West African cuisine.",
      recipesCount: 22,
    },
    comments: [
      {
        id: "c7",
        author: {
          name: "Emily Taylor",
          avatar: "/images/avatar-11.jpg",
        },
        content: "I've always wanted to try making foo-foo at home, and this recipe made it so easy!",
        date: "1 month ago",
      },
    ],
  },
  {
    id: "7",
    name: "Binch (Black-eyed Peas Stew)",
    description:
      "A hearty stew made with black-eyed peas, meat, and vegetables. It's a nutritious and filling dish that's popular in Sierra Leone.",
    image: "/images/binch.jpg",
    cookTime: 75,
    servings: 6,
    approvalRating: 87,
    votes: 65,
    ingredients: [
      { name: "black-eyed peas", quantity: "2 cups" },
      { name: "beef", quantity: "1 lb" },
      { name: "onions", quantity: "2 medium" },
      { name: "tomatoes", quantity: "3 medium" },
      { name: "palm oil", quantity: "1/4 cup" },
      { name: "hot peppers", quantity: "1-2" },
      { name: "salt", quantity: "to taste" },
      { name: "Maggi cubes", quantity: "2" },
    ],
    instructions: [
      "Soak the black-eyed peas in water overnight. Drain and rinse.",
      "Cut the beef into bite-sized pieces.",
      "In a large pot, heat the palm oil over medium heat.",
      "Add the onions and sauté until translucent.",
      "Add the beef and cook until browned on all sides.",
      "Add the tomatoes and cook for 5 minutes.",
      "Add the black-eyed peas, hot peppers, salt, and Maggi cubes.",
      "Add enough water to cover the ingredients and bring to a boil.",
      "Reduce heat and simmer for 45-60 minutes until the peas are soft and the stew thickens.",
      "Serve hot with rice or bread.",
    ],
    tips: [
      "Soaking the peas overnight reduces cooking time and makes them easier to digest.",
      "You can add other vegetables like carrots or bell peppers for extra nutrition.",
      "For a vegetarian version, omit the meat and use vegetable stock.",
    ],
    categories: ["Main Dish", "Stew", "Legumes"],
    author: {
      name: "Fatmata Sesay",
      avatar: "/images/avatar-6.jpg",
      bio: "Cooking enthusiast sharing traditional Sierra Leonean recipes from my grandmother's kitchen.",
      recipesCount: 8,
    },
    comments: [
      {
        id: "c8",
        author: {
          name: "Michael Johnson",
          avatar: "/images/avatar-12.jpg",
        },
        content: "This binch is so flavorful! I added some carrots and it was perfect.",
        date: "2 weeks ago",
      },
    ],
  },
  {
    id: "8",
    name: "Akara (Black-eyed Pea Fritters)",
    description:
      "Crispy fritters made from black-eyed peas. They're a popular street food and breakfast item in Sierra Leone.",
    image: "/images/akara.jpg",
    cookTime: 40,
    servings: 4,
    approvalRating: 89,
    votes: 72,
    ingredients: [
      { name: "black-eyed peas", quantity: "2 cups" },
      { name: "onions", quantity: "1 large" },
      { name: "hot peppers", quantity: "1-2" },
      { name: "salt", quantity: "to taste" },
      { name: "vegetable oil", quantity: "for frying" },
    ],
    instructions: [
      "Soak the black-eyed peas in water for at least 4 hours or overnight. Drain.",
      "Remove the skins from the peas by rubbing them between your hands under running water.",
      "Blend the peeled peas with the onions and hot peppers until smooth.",
      "Add salt to taste and mix well.",
      "Heat oil in a deep pan for frying.",
      "Drop spoonfuls of the batter into the hot oil and fry until golden brown on both sides.",
      "Remove and drain on paper towels.",
      "Serve hot as a snack or breakfast with hot sauce or bread.",
    ],
    tips: [
      "Make sure to remove the skins thoroughly for a smooth texture.",
      "The batter should be thick enough to hold its shape when dropped into the oil.",
      "You can add chopped herbs like parsley for extra flavor.",
    ],
    categories: ["Breakfast", "Snack", "Street Food"],
    author: {
      name: "Mohamed Bangura",
      avatar: "/images/avatar-8.jpg",
      bio: "Fisherman and cook from Freetown, specializing in seafood dishes.",
      recipesCount: 12,
    },
    comments: [
      {
        id: "c9",
        author: {
          name: "Jennifer Lee",
          avatar: "/images/avatar-13.jpg",
        },
        content: "These fritters are amazing! Crispy outside and soft inside.",
        date: "5 days ago",
      },
    ],
  },
  {
    id: "9",
    name: "Pepper Soup",
    description:
      "A spicy, light soup made with meat or fish and a blend of aromatic spices. It's known for its medicinal properties and is often served during cold weather or illness.",
    image: "/images/pepper-soup.jpg",
    cookTime: 60,
    servings: 4,
    approvalRating: 91,
    votes: 88,
    ingredients: [
      { name: "goat meat or fish", quantity: "2 lbs" },
      { name: "onions", quantity: "1 large" },
      { name: "hot peppers", quantity: "3-4" },
      { name: "ginger", quantity: "2 inch piece" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "pepper soup spice mix", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" },
      { name: "water", quantity: "8 cups" },
    ],
    instructions: [
      "Cut the meat or fish into bite-sized pieces.",
      "In a large pot, bring the water to a boil.",
      "Add the meat or fish and boil for 10 minutes.",
      "Add the onions, hot peppers, ginger, garlic, pepper soup spice mix, and salt.",
      "Reduce heat and simmer for 30-45 minutes until the meat is tender.",
      "Adjust seasoning to taste.",
      "Serve hot as a soup or with rice.",
    ],
    tips: [
      "Pepper soup is traditionally very spicy, but you can adjust the heat to your preference.",
      "The pepper soup spice mix can be found in African grocery stores or made at home with a blend of spices.",
      "This soup is believed to have medicinal properties and is often served to new mothers or those recovering from illness.",
    ],
    categories: ["Soup", "Traditional", "Medicinal"],
    author: {
      name: "Ibrahim Koroma",
      avatar: "/images/avatar-4.jpg",
      bio: "Chef and food enthusiast specializing in West African cuisine.",
      recipesCount: 22,
    },
    comments: [
      {
        id: "c10",
        author: {
          name: "Thomas Wright",
          avatar: "/images/avatar-14.jpg",
        },
        content: "This soup cleared my sinuses right up! Delicious and healing.",
        date: "1 week ago",
      },
    ],
  },
  {
    id: "10",
    name: "Coconut Rice",
    description:
      "A flavorful rice dish cooked with coconut milk, giving it a rich, creamy texture and subtle sweetness. It's often served at celebrations and special occasions.",
    image: "/images/coconut-rice.jpg",
    cookTime: 45,
    servings: 6,
    approvalRating: 43,
    votes: 95,
    ingredients: [
      { name: "long grain rice", quantity: "3 cups" },
      { name: "coconut milk", quantity: "2 cans (13.5 oz each)" },
      { name: "water", quantity: "1 cup" },
      { name: "onions", quantity: "1 large" },
      { name: "vegetable oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" },
      { name: "sugar", quantity: "1 tsp (optional)" },
    ],
    instructions: [
      "Wash the rice thoroughly and drain.",
      "Dice the onion finely.",
      "In a large pot, heat the oil over medium heat.",
      "Add the onions and sauté until translucent.",
      "Add the rice and stir for 2-3 minutes until well coated with oil.",
      "Pour in the coconut milk and water. Add salt and sugar (if using).",
      "Bring to a boil, then reduce heat to low.",
      "Cover and simmer for 20-25 minutes until the rice is cooked and the liquid is absorbed.",
      "Fluff with a fork and serve hot.",
    ],
    tips: [
      "For extra flavor, you can add a cinnamon stick or a few cardamom pods while cooking.",
      "This rice pairs well with grilled fish or chicken.",
      "You can garnish with toasted coconut flakes for extra texture and flavor.",
    ],
    categories: ["Side Dish", "Rice", "Celebration Food"],
    author: {
      name: "Aminata Kamara",
      avatar: "/images/avatar-1.jpg",
      bio: "Born and raised in Freetown, I love sharing authentic Sierra Leonean recipes passed down through generations.",
      recipesCount: 15,
    },
    comments: [
      {
        id: "c11",
        author: {
          name: "Sophia Rodriguez",
          avatar: "/images/avatar-15.jpg",
        },
        content: "This coconut rice is amazing! So creamy and flavorful.",
        date: "3 days ago",
      },
    ],
  },
]
